require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to test the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator. If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails. There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.

RSpec.describe "/api/v1/receivables", type: :request do
  let(:company) { create(:company) }

  # This should return the minimal set of attributes required to create a valid
  # Receivable. As you add validations to Receivable, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) {
    {
      net_value: Faker::Commerce.price,
      expired_at: Faker::Date.forward(days: 23),
      key: Faker::Internet.uuid,
      company_id: company.id
    }
  }

  let(:invalid_attributes) {
    {
      net_value: Faker::Commerce.price,
      expired_at: nil,
      key: nil,
      company_id: company.id
    }
  }

  # This should return the minimal set of values that should be in the headers
  # in order to pass any filters (e.g. authentication) defined in
  # ReceivablesController, or in your router and rack
  # middleware. Be sure to keep this updated too.
  let(:valid_headers) {
    {}
  }

  describe "GET /index" do
    it "renders a successful response" do
      Receivable.create! valid_attributes
      get api_v1_receivables_url, headers: valid_headers, as: :json
      expect(response).to be_successful
    end
  end

  describe "GET /show" do
    it "renders a successful response" do
      receivable = Receivable.create! valid_attributes
      get api_v1_receivable_url(receivable), as: :json
      expect(response).to be_successful
    end
  end

  describe "POST /create" do
    context "with valid parameters" do
      it "creates a new Receivable" do
        expect {
          post api_v1_receivables_url,
               params: { receivable: valid_attributes }, headers: valid_headers, as: :json
        }.to change(Receivable, :count).by(1)
      end

      it "renders a JSON response with the new receivable" do
        post api_v1_receivables_url,
             params: { receivable: valid_attributes }, headers: valid_headers, as: :json
        expect(response).to have_http_status(:created)
        expect(response.content_type).to match(a_string_including("application/json; charset=utf-8"))
      end
    end

    context "with invalid parameters" do
      it "does not create a new Receivable" do
        expect {
          post api_v1_receivables_url,
               params: { receivable: invalid_attributes }, as: :json
        }.to change(Receivable, :count).by(0)
      end

      it "renders a JSON response with errors for the new receivable" do
        post api_v1_receivables_url,
             params: { receivable: invalid_attributes }, headers: valid_headers, as: :json
        expect(response).to have_http_status(:unprocessable_entity)
        expect(response.content_type).to eq("application/json; charset=utf-8")
      end
    end
  end

  describe "PATCH /update" do
    context "with valid parameters" do
      let(:new_attributes) {
        {
          net_value: Faker::Commerce.price,
          expired_at: Faker::Date.forward(days: 23),
          key: Faker::Internet.uuid
        }
      }

      it "updates the requested receivable" do
        receivable = Receivable.create! valid_attributes
        patch api_v1_receivable_url(receivable),
              params: { receivable: new_attributes }, headers: valid_headers, as: :json
        receivable.reload
        expect(receivable.net_value.to_f).to eq(new_attributes[:net_value])
        expect(receivable.expired_at).to eq(new_attributes[:expired_at])
        expect(receivable.key).to eq(new_attributes[:key])
      end

      it "renders a JSON response with the receivable" do
        receivable = Receivable.create! valid_attributes
        patch api_v1_receivable_url(receivable),
              params: { receivable: new_attributes }, headers: valid_headers, as: :json
        expect(response).to have_http_status(:ok)
        expect(response.content_type).to match(a_string_including("application/json; charset=utf-8"))
      end
    end

    context "with invalid parameters" do
      it "renders a JSON response with errors for the receivable" do
        receivable = Receivable.create! valid_attributes
        patch api_v1_receivable_url(receivable),
              params: { receivable: invalid_attributes }, headers: valid_headers, as: :json
        expect(response).to have_http_status(:unprocessable_entity)
        expect(response.content_type).to eq("application/json; charset=utf-8")
      end
    end
  end

  describe "DELETE /destroy" do
    it "destroys the requested receivable" do
      receivable = Receivable.create! valid_attributes
      expect {
        delete api_v1_receivable_url(receivable), headers: valid_headers, as: :json
      }.to change(Receivable, :count).by(-1)
    end
  end
end
